---

- name: Install PHP packages
  apt: name={{ item }} state=present
  with_items:
      - php5
      - php5-cli
      - php5-imagick
      - php5-curl
      - php5-gd
      - php5-fpm
      - php5-memcache
      - php5-memcached
      - php5-xdebug
      - php-apcu
      - phpunit